###########################################################
# インサートモードに入ったら読み込む                             #
###########################################################
# 補完
[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = 'has("lua")'
on_i = 1

# 補完 初回「:UpdateRemotePlugins」をする
[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1

# スニペット
[[plugins]]
repo = 'Shougo/neosnippet'
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

# php補完 初回「:PhpMakeDict ja」をする
# [[plugins]]
# repo = 'violetyk/neocomplete-php.vim'
# if = 'has("lua")'
# on_i = 1
# depends = ['neocomplete.vim']
