# プラグインマネージャ
[[plugins]]
repo = 'Shougo/dein.vim'

# 統合ユーザインターフェース
[[plugins]]
repo  = 'Shougo/unite.vim'

# カラースキーマ
[[plugins]]
repo = 'crusoexia/vim-monokai'

# 非同期処理を実現する
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# 移動補助
[[plugins]]
repo  = 'easymotion/vim-easymotion'

# プロジェクト内のファイルやバッファ、履歴からファイルを検索
[[plugins]]
repo  = 'ctrlpvim/ctrlp.vim'

# j/kによる移動を速くする
[[plugins]]
repo = 'rhysd/accelerated-jk'

# 自動的にとじ括弧を挿入
[[plugins]]
repo = 'cohama/lexima.vim'

# grepにagを使う
[[plugins]]
repo = 'rking/ag.vim'

# シンタックスチェック
[[plugins]]
repo  = 'scrooloose/syntastic'

# スニペット集
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# インデントをわかりやすくする
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# gitで管理しているファイルの変更行を表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

# ステータスラインカスタマイズ
[[plugins]]
repo = 'itchyny/lightline.vim'

# ディレクトリツリー表示
[[plugins]]
repo = 'scrooloose/nerdtree'
# ディレクトリツリーに変更記号等を表示
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

# コピペ履歴
# [[plugins]]
# repo  = 'Shougo/neoyank.vim'

# windowの幅調整をしやすくする
# [[plugins]]
# repo = 'simeji/winresizer'

# 任意の単語や文字列をハイライト表示
# [[plugins]]
# repo = 't9md/vim-quickhl'


# 括弧や引用符などを編集
# [[plugins]]
# repo = 'tpope/vim-surround'

# コメントアウト
# [[plugins]]
# repo = 'tomtom/tcomment_vim'

